version: '3.8'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: garnet
      POSTGRES_PASSWORD: garnet-liu
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-mewtwochips:
    image: postgres:latest
    container_name: postgres-mewtwochips
    environment:
      POSTGRES_USER: garnet
      POSTGRES_PASSWORD: garnet-liu
      POSTGRES_DB: auth-mewtwochips
    ports:
      - "5434:5432"
    volumes:
      - postgres_mewtwochips_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
  postgres_mewtwochips_data: