packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp

patchedDependencies:
  graphql-tag: patches/graphql-tag.patch
  pokenode-ts: patches/pokenode-ts.patch

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
